version: 0.2

phases:
  pre_build:
    commands:
      - echo Fazendo login no Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $(aws sts get-caller-identity --query Account --output text).dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=$(aws sts get-caller-identity --query Account --output text).dkr.ecr.us-east-1.amazonaws.com/coworking-analytics
      - IMAGE_TAG=1.0.0
  build:
    commands:
      - echo Build iniciado em `date`
      - echo Construindo a imagem Docker...
      - cd analytics
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build concluído em `date`
      - echo Enviando imagem para o ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG