apiVersion: v1
kind: Service
metadata:
  name: local-coworking-analytics
  labels:
    app: local-coworking-analytics
spec:
  type: ClusterIP
  selector:
    app: local-coworking-analytics
  ports:
  - port: 5153
    targetPort: 5153
    protocol: TCP
